---
driver:
  name: vagrant
  customize:
    memory: 6144
    cpuexecutioncap: 50
  gui: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.3

platforms:
  - name: windows-2016
  - name: windows-2012r2
  - name: windows-2008r2
  - name: windows-7
  - name: windows-81

suites:
  - name: insights
    driver:
      synced_folders:
        - ["/arcgis/setups/windows/ArcGIS_Server", "C:/temp/setups/ArcGIS_Server"]
        - ["/arcgis/setups/windows/Insights_for_ArcGIS", "C:/temp/setups/Insights"]
        - ["/arcgis/setups/authorization_files/Version10.6/ArcGIS_Server/Advanced", "C:/temp/auth_files/ArcGIS_Server"]
    run_list:
      - recipe[arcgis-enterprise::system]
      - recipe[arcgis-enterprise::server]
      - recipe[arcgis-insights]
    attributes:
      arcgis:
        version: "10.6"
        hosts:
          test.com: ""
        server:
          setup: "C:\\temp\\setups\\ArcGIS_Server\\Setup.exe"
          authorization_file: "C:\\temp\\auth_files\\ArcGIS_Server\\Server_Ent_Adv.ecp"
          url: "http://test.com:6080/arcgis"
          domain_name: "test.com"
        insights:
          version: "1.0"
          setup: "C:\\temp\\setups\\Insights\\Setup.exe"
