---
driver:
  name: vagrant
  customize:
    memory: 8192
    cpus: 4
    cpuexecutioncap: 75
  gui: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.3

platforms:
  - name: windows-2016
  - name: windows-2012r2
  - name: windows-2008r2
  - name: windows-7
  - name: windows-81
  - name: centos-6.7
  - name: centos-7.2
  - name: ubuntu-16.04

suites:
  - name: webgis
    driver:
      network:
        - ["forwarded_port", {guest: 6080, host: 16080}]
        - ["forwarded_port", {guest: 6443, host: 16443}]
        - ["forwarded_port", {guest: 7443, host: 17443}]
      synced_folders:
        - ["/arcgis/setups/windows/ArcGIS_Server", "C:/temp/setups/ArcGIS_Server"]
        - ["/arcgis/setups/windows/ArcGIS_DataStore", "C:/temp/setups/ArcGIS_DataStore"]
        - ["/arcgis/setups/windows/Portal_for_ArcGIS", "C:/temp/setups/Portal_for_ArcGIS"]
        - ["/arcgis/setups/windows/ArcGIS_WebAdaptorIIS", "C:/temp/setups/WebAdaptorIIS"]
        - ["/arcgis/setups/authorization_files/Version10.6/ArcGIS_Server/Advanced", "C:/temp/authorization_files/ArcGIS_Server"]
        - ["/arcgis/setups/authorization_files/Version10.6/Portal_for_ArcGIS", "C:/temp/authorization_files/Portal_for_ArcGIS"]
        - ["/data", "C:/temp/data"]
    run_list:
      - recipe[arcgis-enterprise::enterprise_validate]
      - recipe[arcgis-enterprise::system]
      - recipe[esri-iis]
      - recipe[arcgis-enterprise::server]
      - recipe[arcgis-enterprise::server_security]
      - recipe[arcgis-enterprise::server_wa]
      - recipe[arcgis-enterprise::datastore]
      - recipe[arcgis-enterprise::portal]
      - recipe[arcgis-enterprise::portal_wa]
      - recipe[arcgis-enterprise::federation]
      - recipe[arcgis-enterprise::services]
      - recipe[arcgis-enterprise::enterprise_uninstalled]
      - recipe[arcgis-enterprise::clean]
    attributes:
      chef_client:
        config:
          log_level: ":debug"
      arcgis:
        version: "10.6"
        configure_windows_firewall: true
        hosts:
          test.com: ""
        server:
          setup: "C:\\temp\\setups\\ArcGIS_Server\\Setup.exe"
          authorization_file: "C:\\temp\\authorization_files\\ArcGIS_Server\\Server_Ent_Adv.ecp"
          wa_url: "http://test.com/server"
          url: "http://test.com:6080/arcgis"
          domain_name: "test.com"
          services:
            - name: "map_bv"
              folder: ""
              type: "MapServer"
              definition_file: "C:/temp/data/map_bv.sd"
              properties:
                maxInstancesPerNode: 4
        data_store:
          setup: "C:\\temp\\setups\\ArcGIS_DataStore\\Setup.exe"
        portal:
          setup: "C:\\temp\\setups\\Portal_for_ArcGIS\\Setup.exe"
          authorization_file: "C:\\temp\\authorization_files\\Portal_for_ArcGIS\\portal_25_50.ecp"
          wa_url: "https://test.com/portal"
          url: "https://test.com:7443/arcgis"
          domain_name: "test.com"
        web_adaptor:
          setup: "C:\\temp\\setups\\WebAdaptorIIS\\Setup.exe"
    excludes:
      - centos-6.7
      - centos-7.2
      - ubuntu-16.04

  - name: webgis-linux
    driver:
      network:
        - ["forwarded_port", {guest: 6080, host: 26080}]
        - ["forwarded_port", {guest: 6443, host: 26443}]
        - ["forwarded_port", {guest: 7443, host: 27443}]
      synced_folders:
        - ["/arcgis/setups/linux/ArcGISServer", "/tmp/server-cd"]
        - ["/arcgis/setups/linux/ArcGISDataStore", "/tmp/data-store-cd"]
        - ["/arcgis/setups/linux/ArcGISPortal", "/tmp/portal-cd"]
        - ["/arcgis/setups/linux/WebAdaptor", "/tmp/web-adaptor-cd"]
        - ["/arcgis/setups/authorization_files/Version10.6/ArcGIS_Server/Advanced", "/tmp/authorization_files/ArcGISServer"]
        - ["/arcgis/setups/authorization_files/Version10.6/Portal_for_ArcGIS", "/tmp/authorization_files/ArcGISPortal"]
    run_list:
      - recipe[arcgis-enterprise::system]
      - recipe[esri-tomcat]
      - recipe[iptables]
      - recipe[arcgis-enterprise::iptables]
      - recipe[arcgis-enterprise::server]
      - recipe[arcgis-enterprise::server_wa]
      - recipe[arcgis-enterprise::datastore]
      - recipe[arcgis-enterprise::portal]
      - recipe[arcgis-enterprise::portal_wa]
      - recipe[arcgis-enterprise::federation]
      - recipe[arcgis-enterprise::patches]
    attributes:
      java:
        install_flavor: "oracle"
        jdk_version: "8"
        oracle:
          accept_oracle_download_terms: true
      arcgis:
        version: "10.6"
        hosts:
          test.com: ""
        server:
          setup: "/tmp/server-cd/Setup"
          authorization_file: "/tmp/authorization_files/ArcGISServer/Server_Ent_Adv.ecp"
          wa_url: "http://test.com/server"
          url: "http://test.com:6080/arcgis"
          domain_name: "test.com"
        data_store:
          setup: "/tmp/data-store-cd/Setup"
        portal:
          setup: "/tmp/portal-cd/Setup"
          authorization_file: "/tmp/authorization_files/ArcGISPortal/portal_25_50.ecp"
          wa_url: "https://test.com/portal"
          url: "https://test.com:7443/arcgis"
          domain_name: "test.com"
        web_adaptor:
          setup: "/tmp/web-adaptor-cd/Setup"
        web_server:
          webapp_dir: "/opt/tomcat_arcgis/webapps"
    excludes:
      - windows-2016
      - windows-2012r2
      - windows-2008r2
      - windows-7
      - windows-81
